POST http://localhost:8081/cadastrar
Content-Type: application/json

{
  "nome": "José Stevart",
  "cpf": "111.111.111-11",
  "usuario": "stevart@hotmail.com",
  "senha": "irmadostevart123",
  "grupo": "ADMINISTRADOR"
}
