PUT http://localhost:8081/clientes/alterar
Content-Type: application/json

{
  "id": 2,
  "nome": "Stevart Guerra",
  "cpf": "111.111.111-11",
  "dataNascimento": "2012-04-23T18:25:43.511Z",
  "genero": "Masculino",
  "usuario": "stevart@hotmail.com",
  "senha": "123",
  "enderecoFaturamento": {
    "id": 1,
    "logradouro": "Rua Nova1",
    "numero": 1,
    "complemento": "Bloco 1",
    "bairro": "Teste1",
    "cidade": "Teste1",
    "uf": "TS1",
    "cep": "11111-111"
  },
  "enderecoEntrega": [
    {
      "id": 1,
      "logradouro": "Rua Teste1",
      "numero": 1,
      "complemento": "Bloco 1",
      "bairro": "Teste1",
      "cidade": "Teste1",
      "uf": "TS1",
      "cep": "11111-111",
      "tipoEndereco" : "PRINCIPAL"
    },
    {
      "id": 2,
      "logradouro": "Rua Teste2",
      "numero": 2,
      "complemento": "Bloco 2",
      "bairro": "Teste2",
      "cidade": "Teste2",
      "uf": "TS2",
      "cep": "22222-222",
      "tipoEndereco" : "SECUNDARIO"
    },
    {
      "id": 3,
      "logradouro": "Rua Teste3",
      "numero": 3,
      "complemento": "Bloco 3",
      "bairro": "Teste3",
      "cidade": "Teste3",
      "uf": "TS2",
      "cep": "33333-333",
      "tipoEndereco" : "SECUNDARIO"
    }
  ]
}